import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zach's Games!",
  description: "Generated by Next.js + Sanity.io",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all the pages
  const pages = await getPages();

  return (
    <html lang='en'>
      <body className='max-w-4xl mx-auto py-10'>
        <header className='flex items-center justify-between'>
          <Link
            href='/'
            className='bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent font-extrabold'
          >
            Zach's Games
          </Link>

          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link
                href={`/${page.slug}`}
                key={page._id}
                className='hover:underline'
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  );
}
